# Generated by Django 4.2.24 on 2025-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250, null=True)),
                ('author_name', models.CharField(max_length=250, null=True)),
                ('ISBN_no', models.CharField(max_length=250, null=True)),
                ('published_date', models.DateField()),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
