# Generated by Django 4.2.24 on 2025-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='bought_in',
            field=models.CharField(max_length=250, null=True),
        ),
    ] 
