# Generated by Django 4.2.24 on 2025-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_bookdetails_bought_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='book_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
