# Generated by Django 4.2.24 on 2025-09-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_summary_bookdetails_detailed_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='bought_in',
        ),
    ]
