# Generated by Django 4.2.24 on 2025-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookersdetails',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookersdetails',
            name='contributed_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
