# Generated by Django 4.2.24 on 2025-09-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=250, null=True)),
                ('booker_pic', models.ImageField(null=True, upload_to='pic/')),
                ('contribution', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
