# Generated by Django 4.2.24 on 2025-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookers', '0002_bookersdetails_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookersdetails',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
