# Generated by Django 4.2.24 on 2025-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_bookdetails_book_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='summary',
            new_name='detailed_summary',
        ),
        migrations.RemoveField(
            model_name='bookdetails',
            name='ISBN_no',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='contributor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='front_page_summary',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
